### ISSUE TITLE
Readme has conflicting data

### ISSUE THREAD

**Issue by AbdealiLoKo** [Pendrokar/SublimeLinter-contrib-csharplint#2]
The readme says charplint is not a linter (software) but then asks to install csharplint from a package manager ?

**Comment by Pendrokar** [comment]
And before that there is this line "Everything after this sentence is the default README that is created by Sublime Linter 3". Why? Because I was that lazy.

Normally what follows "-contrib-" is the name of the linter for the programming language. What I used in my case was the Mono compiler in error check mode. Not really a linter.

You may clone this package in your Sublime Packages directory and have the command "mcs" be directed to the compiler(IIRC cs command or mcs(for Mono)) or just modify the linter.py file. I was using this for Unity 3D, which has its own Mono installation that comes with it.

**Comment by Pendrokar** [comment]
Made the readme more clarifying. Reply if you are facing problems.
